### ISSUE TITLE
Question about the fine tuning with some real images.

### ISSUE THREAD

**Issue by MonteWa** [gulvarol/surreal#11]
Hi, 

Thanks a lot for your work. I have learned much from this project.

And I have a question about the fine tunning. You have mentioned it in your paper , that with fine tuning with some real training data, you have improved the network a lot. So i'd like to know how did you implement the fine tuning? Did you add one more conv layer after the trained network and then training the whole network more iterations with some real data?

Could you please explain more about it, thanks!

**Comment by gulvarol** [comment]
Since the definition of the classes (body parts or depth bins) did not change from synthetic dataset to real dataset, we took the network trained on synthetic as it is without changing the architecture and then resumed training with the real images only, with less iterations compared to the synthetic pre-training.

**Comment by MonteWa** [comment]
I got that, thanks for your answer!
