### ISSUE TITLE
What does "ung_" mean?

### ISSUE THREAD

**Issue by koelscha** [gulvarol/surreal#21]
Many of the clips have the prefix "ung_" in their sequence name. I wonder what this means and if these sequences should be treated different.

**Comment by gulvarol** [comment]
It stands for 'ungendered'. This is the output of MoSH fitting to the CMU MoCap data. When we retarget the SMPL parameters for synthetic data creation, we do not use the original gender and randomly pick a gender, so it was ignored for this project.

**Comment by koelscha** [comment]
I see. Thank you!

I have one more question: What do the 30%, 50% and 70% overlap mean? I first thought, overlap means that there are frames which exist in multiple clips, but I could not find such clips.

**Comment by gulvarol** [comment]
The overlap is on the mocap sequences. CMU motion capture data has very long sequences. In order to diversify the videos, we used the mocap frames with some overlap and broke them into 100-frame clips. But at each time, we randomly sample everything else so the frames do not match in appearance. The common thing is just the 3D motion.
