### ISSUE TITLE
Problem in the datageneration

### ISSUE THREAD

**Issue by elammarin** [gulvarol/surreal#56]
I have set the variables of run.sh and of the config file correctly and it gives me this error when I run `run.sh`. I understand that AVERAGE is not part of the enum but I don't know what to replace by especially that AVERAGE isn't and doesn't look like an operation.
Can someone gives me a hint ?

```bash 
Traceback (most recent call last):
  File "/home/pji/surreal/datageneration/main_part1.py", line 826, in <module>
    main()
  File "/home/pji/surreal/datageneration/main_part1.py", line 553, in main
    create_sh_material(mat_tree, sh_dst, cloth_img)
  File "/home/pji/surreal/datageneration/main_part1.py", line 178, in create_sh_material
    uv_xform.operation = 'AVERAGE'
TypeError: bpy_struct: item.attr = val: enum "AVERAGE" not found in ('ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'CROSS_PRODUCT', 'PROJECT', 'REFLECT', 'DOT_PRODUCT', 'DISTANCE', 'LENGTH', 'SCALE', 'NORMALIZE', 'SNAP', 'FLOOR', 'CEIL', 'MODULO', 'FRACTION', 'ABSOLUTE', 'MINIMUM', 'MAXIMUM')

Blender quit
```

**Comment by gulvarol** [comment]
Thanks for reporting this. Maybe [this link](https://blender.stackexchange.com/questions/187440/where-is-the-average-setting-in-the-vector-math-node) can help, i.e., replacing with ADD+NORMALIZE.

**Comment by mnauf** [comment]
@gulvarol 
  File "/datadrive/SURREAL/surreal/datageneration/main_part1.py", line 180, in create_sh_material
    uv_xform.operation = 'ADD+NORMALIZE'
TypeError: bpy_struct: item.attr = val: enum "ADD+NORMALIZE" not found in ('ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'MULTIPLY_ADD', 'CROSS_PRODUCT', 'PROJECT', 'REFLECT', 'REFRACT', 'FACEFORWARD', 'DOT_PRODUCT', 'DISTANCE', 'LENGTH', 'SCALE', 'NORMALIZE', 'ABSOLUTE', 'MINIMUM', 'MAXIMUM', 'FLOOR', 'CEIL', 'FRACTION', 'MODULO', 'WRAP', 'SNAP', 'SINE', 'COSINE', 'TANGENT')

**Comment by mnauf** [comment]
@gulvarol 
File "/datadrive/SURREAL/surreal/datageneration/main_part1.py", line 180, in create_sh_material
uv_xform.operation = 'ADD+NORMALIZE'
TypeError: bpy_struct: item.attr = val: enum "ADD+NORMALIZE" not found in ('ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'MULTIPLY_ADD', 'CROSS_PRODUCT', 'PROJECT', 'REFLECT', 'REFRACT', 'FACEFORWARD', 'DOT_PRODUCT', 'DISTANCE', 'LENGTH', 'SCALE', 'NORMALIZE', 'ABSOLUTE', 'MINIMUM', 'MAXIMUM', 'FLOOR', 'CEIL', 'FRACTION', 'MODULO', 'WRAP', 'SNAP', 'SINE', 'COSINE', 'TANGENT')

**Comment by mnauf** [comment]
@gulvarol Are you sure you used 2.78 blender? Because I have looked into documentation of the following and there is no ENUM AVERAGE:

[blender_python_api_2_78c_release/](https://docs.blender.org/api/blender_python_api_2_78c_release/)
[blender_python_api_2_78b_release/](https://docs.blender.org/api/blender_python_api_2_78b_release/)
[blender_python_api_2_78a_release/](https://docs.blender.org/api/blender_python_api_2_78a_release/)
[blender_python_api_2_78_release/](https://docs.blender.org/api/blender_python_api_2_78_release/)
[blender_python_api_2_78_4/](https://docs.blender.org/api/blender_python_api_2_78_4/)	
[blender_python_api_2_78_3/](https://docs.blender.org/api/blender_python_api_2_78_3/)	
[blender_python_api_2_78_1/](https://docs.blender.org/api/blender_python_api_2_78_1/)	
[blender_python_api_2_78_0/](https://docs.blender.org/api/blender_python_api_2_78_0/)
